name: Lint and Test

on:
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Setup Node
                uses: actions/setup-node@v1
                with:
                    node-version: 16

            -   uses: actions/checkout@v2

            -   name: Install Dependencies
                run: yarn install --no-progress --silent

            -   name: Lint
                run: yarn lint
